### ISSUE TITLE
make找不到CMSIS_5/Source/

### ISSUE THREAD

**Issue by hpycuit** [JeffyCN/ARM-KWS-demo#1]
你好，我按照你的Quick start的步骤在step 4的时候遇到了问题，当我使用make CPU=m4的时候报找不到CMSIS_5/Source/，并且还有其他的一些问题，日志见下方
make CPU=m4
find: `CMSIS_5/Source/': 没有那个文件或目录
find: `CMSIS_5/Source/': 没有那个文件或目录
find: `CMSIS_5/Source/': 没有那个文件或目录
find: `CMSIS_5/Source/': 没有那个文件或目录
find: `CMSIS_5/Source/': 没有那个文件或目录
find: `CMSIS_5/Source/': 没有那个文件或目录
find: `CMSIS_5/Source/': 没有那个文件或目录
Compile: kws.c
In file included from KWS/Deployment/Source//KWS_C/kws.h:22:0,
                 from KWS/Deployment/Source//KWS_C/kws.c:24:
KWS/Deployment/Source//NN_C/nn.h:22:10: fatal error: arm_nnfunctions.h: 没有那个文件或目录
 #include "arm_nnfunctions.h"
          ^~~~~~~~~~~~~~~~~~~
compilation terminated.
Makefile:172: recipe for target 'BUILD/KWS/Deployment/Source//KWS_C/kws.o' failed
make: *** [BUILD/KWS/Deployment/Source//KWS_C/kws.o] Error 1

**Comment by JeffyCN** [comment]
Hi hpycuit,

Thanks for testing!
Sorry about those errors, i uploaded the custom CMSIS to it's master branch, but the default one seems to be develop.

Anyway, these commands should work(the README.md is updated too):
git clone https://github.com/JeffyCN/ARM-KWS-demo.git
git clone https://github.com/JeffyCN/ML-KWS-for-MCU.git
git clone https://github.com/JeffyCN/CMSIS_5.git -b master
cd ARM-KWS-demo/ && make && ./kws_test
