### ISSUE TITLE
quant_dump.sh的問題想請教？

### ISSUE THREAD

**Issue by WEI-TING-LI** [JeffyCN/ARM-KWS-demo#3]
quant_dump.sh在我的pc上找最佳act_max值解出來的weights.h
是否等效於 quant_test.py套用同一組參數解出來的 weights.h

另外quant_dump.sh 總共有12Layer, 我pc跑了一天才跑到Layer3,
是否有方法可以限制跑最佳act_max的Layer數？
謝謝.

ex:
python quant_test.py --data_url= --data_dir=/home/tim/work/share/_code/ML-KWS-for-MCU/Tran2 --wanted_words yes,no,up,down,left,right,on,off,stop,go --clip_duration_ms 1000 --model_architecture ds_cnn --testing_percentage 10 --validation_percentage 10 --training_percentage 80 --unknown_percentage 50 --model_size_info 5 64 10 4 2 2 64 3 3 1 1 64 3 3 1 1 64 3 3 1 1 64 3 3 1 1 --dct_coefficient_count 10 --window_size_ms 40 --window_stride_ms 20 --act_max 32 0 0 0 0 0 0 0 0 0 0 0 --checkpoint work/DS_CNN/training/best/ds_cnn_9380.ckpt-17200_bnfused

是否等效於
python quant_dump.py       --data_url=   --data_dir=/home/tim/work/share/_code/ML-KWS-for-MCU/Tran2   --wanted_words yes,no,up,down,left,right,on,off,stop,go   --clip_duration_ms 1000   --model_architecture ds_cnn   --testing_percentage 10   --validation_percentage 10   --training_percentage 80   --unknown_percentage 50      --model_size_info 5 64 10 4 2 2 64 3 3 1 1 64 3 3 1 1 64 3 3 1 1 64 3 3 1 1   --dct_coefficient_count 10   --window_size_ms 40   --window_stride_ms 20     --act_max 0 0 0 0 0 0 0 0 0 0 0 0  --checkpoint work/DS_CNN/training/best/ds_cnn_9380.ckpt-17200_bnfused
act_max: [32, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

**Comment by JeffyCN** [comment]
1/ Currently, the script is iterating all possible combinations of act_max to find the one with highest accuracy.
And you can try to pass an initial act_max through the '--act_max' argument, the script would start search from the first layer with a non-zero value, (check the start_layer in get_best_act_max(act_max)).

2/ Yes, they are the same. The related part in quant_dump.py is copied from quant_test.py.

**Comment by WEI-TING-LI** [comment]
Thanks for your help, I have understood the subject.
